version: '3.8'

services:
  # Redis service for Sidekiq
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Rails backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DOCKER_ENV=true
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - redis
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0

  # Sidekiq worker
  sidekiq:
    build: ./backend
    environment:
      - RAILS_ENV=development
      - DOCKER_ENV=true
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - redis
      - backend
    restart: unless-stopped
    command: bundle exec sidekiq

  # React frontend
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

volumes:
  redis_data:
  bundle_cache:
